# Contents of /lakehouse-stack/lakehouse-stack/config/nessie/application.properties

nessie.server.url=http://nessie:19120/api/v1
nessie.catalog.type=iceberg
nessie.repository.name=nyc_taxi_repo
nessie.ref.name=main
nessie.ref.type=branch
nessie.auth.type=none
iceberg.catalog.type=nessie
iceberg.nessie.uri=http://nessie:19120
iceberg.nessie.ref=main
iceberg.nessie.repository=nyc_taxi_repo
iceberg.nessie.auth.type=none